### ISSUE TITLE
HTML贴图出现了问题

### ISSUE THREAD

**Issue by EtaoinWu** [liulex/Snipaste-Feedback#443]
发现了 bug？
* 请描述一下重现的步骤，越详细越好
http://www.lydsy.com/JudgeOnline/problem.php?id=3812
这样一个网页
![截图](https://cloud.githubusercontent.com/assets/22369305/25770238/f4333ae8-3262-11e7-9fd8-cc194a421fa5.png)
贴图出现了背景渲染错误，只有第一个内层div标签有外层div标签的background color
![贴图](https://cloud.githubusercontent.com/assets/22369305/25770239/090d3a04-3263-11e7-9029-a81703a65a34.png)
相关网页代码：
```html
<div class="content"><div>响应主旋律的号召，大家决定让这个班级充满爱，现在班级里面有 n 个男生。</div>
<div>如果 a 爱着 b，那么就相当于 a 和 b 之间有一条 a→b 的有向边。如果这 n 个点的图是强联通的，那么就认为这个班级是充满爱的。</div>
<div>不幸的是，有一些不好的事情发生了，现在每一条边都可能被摧毁。我作为爱的使者，想知道有多少种摧毁的方式，使得这个班级任然充满爱呢？（说人话就是有多少边的子集删去之后整个图仍然强联通。）</div>
<p></p></div>
```
```css
div.content {
    height: auto;
    background: #e4f0f8;
    margin: 0;
    padding: 0 20px;
    font-size: 18px !IMPORTANT;
    font-family: Times New Roman;
    text-align: left;
}
```
